import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import { NextIntlClientProvider } from "next-intl"; // Импортируйте провайдер
import { useTranslations } from "next-intl"; // Импортируйте useTranslations, если нужно

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <NextIntlClientProvider locale="en">
      {" "}
      {/* Укажите локаль по умолчанию */}
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Header /> {/* Включите заголовок */}
          {children}
        </body>
      </html>
    </NextIntlClientProvider>
  );
}
